version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.3
    commands:
      - echo "install step"
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "skip build step"
  post_build:
    commands:
      - echo "post_build step"
artifacts:
  files:
    - '**/*'
